package storage

func opts() string {
	return "?_foreign_keys=on&_journal_mode=WAL"
}

func schema() string {
	return `
CREATE TABLE User (
  UserID INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  Email TEXT NOT NULL UNIQUE
);

CREATE TABLE Task (
  TaskID INTEGER PRIMARY KEY AUTOINCREMENT,
  Title TEXT NOT NULL,
  Description TEXT NOT NULL,
  Due DATE NOT NULL,
  Do DATE NOT NULL,
  Owner INTEGER NOT NULL,
  FOREIGN KEY (Owner) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE Tag (
  TagID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL UNIQUE
);

CREATE TABLE TaskTag (
  TaskUUID INTEGER NOT NULL,
  TagID INTEGER NOT NULL,
  PRIMARY KEY (TaskUUID, TagID),
  FOREIGN KEY (TaskUUID) REFERENCES Task(UUID) ON DELETE CASCADE,
  FOREIGN KEY (TagID) REFERENCES Tag(TagID) ON DELETE CASCADE
);
`
}
